# Site/SEO settings
email: narcissuscat@naver.com
permalink: /:year/:month/:day/:title/
google_analytics: 

title: Myolog
description: 프론트엔드 개발자 취준생
url: https://myomyoring.github.io
baseurl:
default_img: https://cdn.pixabay.com/photo/2020/05/06/06/18/blue-5136251_1280.jpg

# Profile settings
name: 묘묘링
profile_img: https://cdn.pixabay.com/photo/2019/04/16/23/25/morning-4133099_1280.jpg
profile: 안녕하세요! 공부 중인 프론트엔드 개발자 취준생, 묘묘링 입니다.
social:
  github: https://github.com/Myomyoring

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - octopress-autoprefixer
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - _screenshots
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - README.md

# Pagination
paginate: 5
paginate_path: "/blog/page-:num"

# Sass
sass:
  style: compressed